[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "desktop-rainworld-slugcat-simulation"
version = "1.0.1"
description = "Rain World ecology simulator focused on slugcat desktop pets, AI, pathfinding, physics, creatures and storms."
readme = "README.md"
license = "MIT"
authors = [
    { name = "littlhMW", email = "littlhMW@users.noreply.github.com" },
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Win32 (MS Windows)",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Programming Language :: Python :: 3",
    "Topic :: Games/Entertainment",
]
dependencies = [
    "PySide6>=6.10.0",
    "UnityPy>=1.23.0",
    "numpy>=2.3.0",
    "Pillow>=12.0.0",
]

[project.urls]
Repository = "https://github.com/littlhMW/desktop-rainworld-slugcat-simulation"

[project.gui-scripts]
desktop-rainworld-slugcat-simulation = "slugcatpet.main:main"
slugcatpet = "slugcatpet.main:main"

[tool.setuptools.packages.find]
include = ["slugcatpet*"]

[tool.setuptools.package-data]
slugcatpet = ["resources/icons/*.svg", "resources/icons/*.png", "resources/audio/*.wav", "resources/layouts/*.json"]
