"""行为参数中枢，tick=1/40s；每猫专属覆盖见 cats/<variant>.CatDef.tuning。"""
from __future__ import annotations

# 心情仲裁打分噪声
MOOD_NOISE_AMP = 0.20

# 趴下休息：体力驱动的强制疲劳
EXHAUST_ENTER_ENERGY = 0.1
EXHAUST_EXIT_ENERGY = 0.50
LIE_SETTLE_TICKS = 40

# 耗能玩法体力门
PLAY_ENERGY_GATE = 0.40

# 性格接线全局旋钮
PERS_ACT_SPREAD  = 1.0
PERS_GATE_SPREAD = 0.20
PERS_GATE_FLOOR  = 0.20


# 爬竖杆权重与新鲜度
POLE_BASE = 1.00
POLE_START = 0.70
POLE_QUIT = 0.30
POLE_INIT = 0.30
POLE_DECAY = 0.0040
POLE_RECOVER = 0.00058
POLE_SF_FRESH = 1.50
POLE_SF_TIRED = 0.10

# 横杆权重与新鲜度
HPOLE_BASE = 1.00
HPOLE_START = 0.72
HPOLE_QUIT = 0.30
HPOLE_INIT = 0.30
HPOLE_DECAY = 0.0035
HPOLE_RECOVER = 0.00060
HPOLE_SF_FRESH = 1.30
HPOLE_SF_TIRED = 0.10

# 上天花板权重与新鲜度
CEIL_BASE = 1.00
CEIL_START = 0.75
CEIL_QUIT = 0.30
CEIL_INIT = 0.10
CEIL_DECAY = 0.0018
CEIL_RECOVER = 0.00038
CEIL_SF_FRESH = 1.30
CEIL_SF_TIRED = 0.15
# 避水闸：涨水强制中断上吊顶
CEIL_WATER_ENERGY_GATE = 0.20

# 发呆兜底候选权重与驻留
IDLE_BASE = 1.00
IDLE_SF_KNEE = 0.9
IDLE_SF_FRESH = 0.30
IDLE_SF_TIRED = 24.0
IDLE_HOLD_MIN = 120
IDLE_HOLD_MAX = 520
IDLE_HOLD_TIRED_MULT = 1.8
IDLE_BREATHER = 50

# 饱食度
FOOD_INIT = 2
FOOD_KILL_PENALTY = 4
EN_EAT_RESTORE = 0.10

# 业力与冬眠
KARMA_INIT = 8
KARMA_MAX = 9
HIBERNATE_TICKS = 3600
REVIVE_TICKS = 50

# 好感
TEMPER_SWING_SPEED = 10.0
TEMPER_SWING_RATE = -0.0008
TEMPER_STUN = -0.25
TEMPER_KILL_CANCEL_HUMAN = -0.10
TEMPER_KILL_REVIVED = -0.50
TEMPER_FEED = 0.20
TEMPER_LICK = 0.10
TEMPER_DECAY = 1.0 / 180000.0

# 寒冷、暴风雪、暖灯供暖、转世
COLD_BLIZZARD_DEFAULT_OFF = True
COLD_BLIZZARD_RAMP   = 2400
COLD_BLIZZARD_HOLD   = 2400
COLD_BLIZZARD_TOTAL  = 2 * COLD_BLIZZARD_RAMP + COLD_BLIZZARD_HOLD
COLD_EXPOSURE        = 1.0
COLD_GAIN_CLAMP_HI   = 0.0055
COLD_LAMP_WARMTH     = 0.0005
COLD_LAMP_RANGE      = 350.0
COLD_LAMP_SCALE      = 0.6
COLD_CRAMP_GAIN_GATE = 0.0003
COLD_DEATH_STUN      = 50
COLD_WARMTH_INNER    = 70.0
COLD_NATURAL_DECAY   = 0.001
REINCARNATE_TICKS    = 600

# 自主趋暖与冻醒
COLD_SEEK_ENTER  = 0.30
COLD_SEEK_EXIT   = 0.10
COLD_NOSLEEP     = 0.20
COLD_SEEK_BASE   = 3.0
COLD_ARRIVE_FRAC = 0.8

# 雪与霜冻氛围
SNOW_ENABLED      = True
SNOW_MAX_FLAKES   = 50
SNOW_VIGNETTE_MAX = 15

# 水环境（默认关）
WATER_FULL_DEPTH = 0.55
WATER_EASE_TICKS = 400
WATER_STILL_EPS  = 0.15
WATER_SPACING    = 20.0
WATER_FLOW       = 0.08
WATER_BODY_RGBA    = (46, 120, 150, 92)
WATER_SURFACE_RGBA = (150, 214, 232, 175)
WATER_THREAT_SAFE_DEPTH = 60.0

# 游泳/憋气/淹死（y↓）
SWIM_ENTER            = 0.2
SWIM_DEEP_DEPTH       = 30.0
SWIM_DEEP_DIVE_DEPTH  = 10.0
SWIM_DEEP_FULL        = 80.0
SWIM_DEEP_HIP_SUB     = 0.6
SWIM_BOOST_MIN_AIR    = 0.5
SWIM_BOOST_DIST       = 60.0
SWIM_SURFACE_HEAD_ABOVE = 15.0
SWIM_LUNG_SUBMERGE    = 0.9
SWIM_DROWN_SUB_HIP    = 0.5
SWIM_DROWN_STEP       = 1.0 / 120.0
SWIM_LUNG_RECOVER     = 60.0
SWIM_LUNG_RECOVER_EXH = 240.0
SWIM_ARRIVE_R         = 34.0
SWIM_FETCH_SEEK_R     = 220.0
SWIM_FETCH_REACH      = 22.0
SWIM_VEL_MAX          = 45.0
SWIM_SURFACE_REST_FAC = 0.5
# 漂游潜深随 swim_zeal 插值
SWIM_DRIFT_DEPTH_MIN  = 15.0
SWIM_DRIFT_DEPTH_MAX  = 70.0
SWIM_DRIFT_DEEP_MAX   = 260.0
SWIM_BOOST_DIST_ZEAL  = 25.0
# 圣徒落水自救：贴墙舌爬出水面
SWIM_ESCAPE_ENERGY    = 0.35
SWIM_ESCAPE_CD        = 200
SWIM_ESCAPE_WALL_REACH = 70.0
PYRO_DEATH_THRESH     = 0.65    # 工匠溺水引爆阈

# 工匠 AI 爆跳：弧线 sim 与 FSM 控制器共用参数
PYRO_BOOST_AIR_TICKS  = 6
PYRO_REACH_MIN_DX     = 140.0

# 工匠爆跳撒欢权重与新鲜度
PYROROMP_BASE = 1.00
PYROROMP_START = 0.72
PYROROMP_QUIT = 0.30
PYROROMP_INIT = 0.30
PYROROMP_DECAY = 0.0040
PYROROMP_RECOVER = 0.00055
PYROROMP_JUMPS = 2

# 溪流后空翻上横杆权重与新鲜度
RIVFLIP_BASE = 1.00
RIVFLIP_START = 0.72
RIVFLIP_QUIT = 0.30
RIVFLIP_INIT = 0.30
RIVFLIP_DECAY = 0.0040
RIVFLIP_RECOVER = 0.00055

# 溺水吐泡
BUBBLE_MAX         = 40
BUBBLE_DRAW_SCALE  = 0.45
BUBBLE_RGBA        = (0, 1, 0)
BUBBLE_OPACITY     = 0.25
BUBBLE_INHERIT_VEL = 0.025
BUBBLE_SPAWN_KICK  = 0.5

# idle 兜底层：东张西望
LOOK_UPDATE_PROB = 0.025
LOOK_NOTHING_PROB = 0.002
LOOK_GLANCE_PROB = 0.002
LOOK_GLANCE_INTEREST = 0.40
LOOK_INTEREST_DECAY_TICKS = 24
LOOK_MIN_INTEREST = 0.20
LOOK_DIST_NEAR = 400.0
LOOK_CURSOR_BASE = 1.00
LOOK_ITEM_BASE = 0.80
# idle 兜底层：踱步
PACE_PROB = 0.0016
# idle 社交走位：按 sociability 决定趋近/远离/随机
SOCIAL_WANDER_LO = 0.4
SOCIAL_WANDER_HI = 0.6
SOCIAL_WANDER_SAMPLES = 11
SOCIAL_WANDER_SIGMA_FRAC = 0.15
SOCIAL_WANDER_MOVE_W = 0.6
SOCIAL_WANDER_CROSS_W = 0.8
SOCIAL_WANDER_STAY_GAIN = 0.05
SOCIAL_WANDER_STAY_SPAN_FRAC = 0.06

# ── 五类欲望（进食/恐惧/战斗/玩耍/睡眠）──
# 爬墙（窗口左右边缘＝墙）
WALL_BASE = 1.00
WALL_START = 0.68
WALL_QUIT = 0.30
WALL_INIT = 0.30
WALL_DECAY = 0.0038
WALL_RECOVER = 0.00058
WALL_SF_FRESH = 1.30
WALL_SF_TIRED = 0.10
WALL_SEEK_R = 90.0            # 墙在这么近内才想起来爬
WALL_CLIMB_TICKS_MIN = 120    # 单次爬墙时长下限
WALL_CLIMB_TICKS_MAX = 420
WALL_WALLJUMP_PROB = 0.02     # 贴墙时每次蹬墙跳的抽样概率
WALL_TOP_GRAB_R = 26.0        # 胸离顶边这么近就转吊顶
WALL_TOP_FULL_PROB = 0.22     # 这面墙直通窗口顶边（能转吊顶）的概率
WALL_TOP_MIN_FRAC = 0.28      # 墙的可攀爬上沿：至少离地这么高（占窗高比例）
WALL_TOP_MAX_FRAC = 0.62      # 最多能爬到这么高：多数墙够不着顶边
WALL_CLIMB_MIN_SPAN = 90.0    # 墙再矮也留这么高的可爬段
WALL_TOP_TIRED_FRAC = 0.45    # 力竭时上沿更低（爬不动这么远）
WALL_LEDGE_HOLD = 26          # 够到墙头后抓沿悬住的 tick
WALL_LEDGE_JUMP_PROB = 0.55   # 抓沿后蹬墙跳（否则松手掉下）

# 被抓：偶尔挣扎（原版 Player 被叼住时蹬腿乱蹬）
DRAG_STRUGGLE_PROB = 0.012    # 每 tick 起挣扎的概率
DRAG_STRUGGLE_MIN_FRAMES = 20 # 刚抓起先愣一下
DRAG_STRUGGLE_TICKS_MIN = 14
DRAG_STRUGGLE_TICKS_MAX = 34
DRAG_STRUGGLE_KICK = 2.6      # 挣扎蹬腿冲量
DRAG_STRUGGLE_VMAX = 3.2      # 自由那截的挣扎速度上限（别甩飞）
DRAG_STRUGGLE_TEMPER = 0.03   # 每次挣扎的心烦增量
DRAG_STRUGGLE_COST = 0.004    # 每次挣扎的体力消耗

# 吊顶（窗口上边缘＝地面/天花）
CEIL_BASE = 1.00
CEIL_START = 0.70
CEIL_QUIT = 0.30
CEIL_INIT = 0.20
CEIL_DECAY = 0.0030
CEIL_RECOVER = 0.00060
CEIL_HANG_TICKS_MIN = 160
CEIL_HANG_TICKS_MAX = 480
CEIL_SHIMMY_PROB = 0.02
CEIL_GRAB_REACH = 96.0        # 跳起来够顶边的判定距离
CEIL_SETTLE_SPEED = 3.0       # 蹭到顶边且慢到这个速度 → 吊住（顶边当平地）
CEIL_WALK_PROB = 0.03         # 吊着时开始沿顶边走动
CEIL_WALK_TICKS_MIN = 20
CEIL_WALK_TICKS_MAX = 70
CEIL_PLACED_TICKS_MIN = 600   # 鼠标放到顶边：愿意多挂一会（10s）
CEIL_PLACED_TICKS_MAX = 1200

# 爆米花（原版外部食物源）：开荚后贴上去啃，每口 +1 饱食
COB_FEED_R = 25.0             # 原版 Custom.DistLess(mainBodyChunk, 最近点, 25f)
COB_EAT_TICKS = 15            # 原版 eatExternalFoodSourceCounter = 15
COB_EAT_CD = 45               # 原版 dontEatExternalFoodSourceCounter = 45
COB_EAT_FOOD = 1              # 原版 AddFood(1)
COB_FEED_SEEK_R = 300.0       # 饿了才会走这么远去啃
COB_REACH_DY = 70.0           # 挂得比胸口高这么多就够不着（跳起来也啃不到）
COB_FEED_TICKS = 600          # 没吃到东西就撤的预算（每吃一口重置）
COB_CHECK_TICKS = 20          # 找豆荚的闸
COB_SEEK_RETRY = 300          # 放弃后的重试冷却
COB_SPEAR_R = 420.0           # 拿矛打未开荚爆米花的距离

# 玩耍：追光标/抓光标（原版蛞蝓猫对移动物体的注意）
PLAYCUR_BASE = 1.00
PLAYCUR_START = 0.66
PLAYCUR_QUIT = 0.30
PLAYCUR_INIT = 0.30
PLAYCUR_DECAY = 0.0042
PLAYCUR_RECOVER = 0.00065
PLAYCUR_SF_FRESH = 1.25
PLAYCUR_SF_TIRED = 0.12
PLAYCUR_R = 320.0             # 光标在此半径内才会想过去
PLAYCUR_ARRIVE = 46.0
PLAYCUR_TICKS_MIN = 120
PLAYCUR_TICKS_MAX = 320
PLAYCUR_GRAB_R = 26.0         # 够得着就伸手抓
PLAYCUR_CHASE_SPEED = 0.7     # 走速比例

# 社交：靠近同伴 / 抚摸同伴 / 指指点点
SOCIAL_BASE = 1.00
SOCIAL_START = 0.62
SOCIAL_QUIT = 0.30
SOCIAL_INIT = 0.25
SOCIAL_DECAY = 0.0030
SOCIAL_RECOVER = 0.00062
SOCIAL_SF_FRESH = 1.20
SOCIAL_SF_TIRED = 0.12
SOCIAL_R = 220.0              # 同伴在此半径内才想凑过去
SOCIAL_ARRIVE = 30.0
SOCIAL_TICKS_MIN = 160
SOCIAL_TICKS_MAX = 420
SOCIAL_POKE_TICKS = 90        # 扒拉/抚摸/指指点点动作时长
SOCIAL_POKE_INTERVAL = 22     # 每次伸手的间隔

# 帮别的猫取食（自己饱了别人没饱）
HELPFEED_SEEK_R = 900.0
HELPFEED_TICKS = 1600
HELPFEED_DROP_R = 40.0

# 被抢东西后的扒拉指指点点
PROTEST_TICKS = 260
PROTEST_R = 240.0

# 战斗（攻击/反击）
FIGHT_R = 320.0
FIGHT_TICKS = 900
FIGHT_THROW_CD = 26
FIGHT_MELEE_R = 40.0          # 够近就用身子撞/抓咬
FIGHT_RECOVER_TICKS = 40      # 反击的迟疑

# 复活同伴：特殊表情（吐舌/舔）扒拉一会儿
REVIVE_TOUCH_R = 26.0
REVIVE_TOUCH_TICKS = 150
REVIVE_APPROACH_TICKS = 900

# 恐惧：匍匐潜行躲避
CRAWL_FEAR_R = 150.0          # 蜥蜴进这个半径 → 趴下潜行
CRAWL_FEAR_SPEED = 0.55       # 匍匐速度比例
CRAWL_AWAY_TICKS = 260

# 睡眠：吃饱后入睡概率从 0 缓慢升到 100
SLEEP_URGE_RATE = 1.0 / 3600.0   # 每 tick 累积（约 90s 到满）
SLEEP_URGE_DECAY = 1.0 / 1800.0  # 没吃饱时回落
SLEEP_CHECK_TICKS = 20           # 每隔这么久掷一次骰

# 站杆顶/横杆面平衡
BAL_FLAIL_PROB = 0.15
BAL_FLAIL_TIP = 6.0
BAL_RECOVER = 0.83
BAL_MAX = 120.0
BAL_COUNTER_WRAP = 300.0
BAL_SWAY_X = 0.08
BAL_SWAY_Y = 0.02

# 站杆顶退出：摔落与主动下杆
TIP_FALL_DISBALANCE = 95.0
TIP_FALL_PROB = 0.04
TIP_TIRED_ENERGY = 0.15
TIP_DISMOUNT_CLIMB_PROB = 0.5
TIP_MIN_TICKS = 40

# 横杆站面拓展：停顿、吊荡、晃动
HP_PAUSE_PROB = 0.02
HP_PAUSE_MIN = 20
HP_PAUSE_MAX = 80
HP_HANG_PROB = 0.0015
HP_HANG_TICKS = 70
# 交叉杆横↔竖切换 + 杆间跳跃（原版 Controls/Pole_Movement：HangFromBeam+上→ClimbOnBeam、
# ClimbOnBeam+侧→HangFromBeam、jump-pole-hopping）
CROSS_DWELL = 3                # 在交点附近待够这么多 tick 才「看见」交叉杆
CROSS_SWITCH_PROB = 0.40       # 看见后每 tick 决定换横/竖的概率
CROSS_PAD = 22.0               # 胸心离交点这么近算「站在交点上」（≈爬杆 10 tick 窗口）
POLE_TIP_HOP_PROB = 0.006      # 杆顶站着时每 tick 想跳到另一根杆的概率
POLE_AIRGRAB_R = 12.0          # 空中贴杆即抓（jump-pole-hopping）
POLE_AIRGRAB_PAD = 10.0        # 杆端外这点范围仍算够得着
POLE_HOP_PROB = 0.30           # 下杆时改为跳向另一根杆的概率
POLE_HOP_SEEK_R = 220.0        # 愿意跳过去的杆间最大距离
POLE_HOP_VX = 4.0              # 跳向另一根杆的横冲量
POLE_HOP_VY = 4.2              # 跳向另一根杆的上抛
HP_WOBBLE_MIN = 30.0
HP_WOBBLE_MAX = 60.0
HP_RETARGET_TICKS = 40

# 吊顶子动作随机化
CEIL_SWAY_AMP_MIN = 0.3
CEIL_SWAY_AMP_MAX = 0.8
CEIL_SWAY_HALF_MIN = 8
CEIL_SWAY_HALF_MAX = 18
CEIL_VMOVE_RANGE = 18.0

# 取物机制常量
GRAB_REACH = 18.0
REACH_GATE_K = 2.0

# 运动规划层：覆盖几何、粗线性代价、执行器失败语义
PLAN_WALK_SPEED = 4.2
PLAN_TONGUE_SPEED = 3.0
PLAN_CLIMB_SPEED = 1.6
PLAN_STARTUP_TICKS = 20.0
PLAN_STAND_REACH_H = 17.0 + GRAB_REACH
PLAN_FLOOR_TOL = 12.0
PLAN_WALK_X_PAD = 30.0
PLAN_MOUTH_H = 22.0
PLAN_TONGUE_RANGE_FRAC = 1.0
PLAN_EN_RATE_LIGHT = 1.0 / 4800.0
PLAN_EN_RATE_VIGOROUS = 1.0 / 1200.0
PLAN_PROGRESS_MIN = 20.0
PLAN_REPLAN_BUDGET = 8
PLAN_COOLDOWN_TICKS = 1200
PLAN_FAILS_PER_SCHEME = 2
PLAN_SCHEMES_MAX = 2
PLAN_STEP_TIMEOUT_MIN = 240.0
PLAN_STEP_TIMEOUT_K = 3.0
PLAN_ARRIVE_EPS = 14.0
PLAN_ARRIVE_HOLD = 30
PLAN_JUMP_HOLD_GEARS = (0, 3, 6)
PLAN_JUMP_TAKEOFF_EPS = 6.0

# 舌锚吊挂驻留参数
PLAN_HANG_WALL_IDEAL = 30.0
PLAN_HANG_BULB_IDEAL = 12.0
PLAN_HANG_CEIL_IDEAL = 50.0
PLAN_HANG_SHOOT_V = 46.7
PLAN_HANG_REEL_RATE = 3.0
PLAN_HANG_ATTACH_TICKS = 40.0
PLAN_HANG_WALL_STOP_FRAC = 0.85
PLAN_HANG_MAX_RECLIMB = 3

# 机会主义舌头补救层：空中掠过果子时抢射舌收回
PLAN_SNATCH_MAX_TRIES = 2
PLAN_SNATCH_TIMEOUT = 120

# 挡路让位：被顶约 1s 顺向让开
SHOVE_CONTACT_DIST = 24.0
SHOVE_YIELD_TICKS  = 40
SHOVE_CLEAR_PAD    = 28.0
MAKEWAY_TIMEOUT    = 200

# 顶人方兜底跳越
BLOCKED_JUMP_TICKS = 100
JUMP_OVER_HOLD     = 6
JUMP_OVER_COOLDOWN = 80
